###########################################################################   
#    name      : security.yaml
#    Role      : describe all security components of univertuel app
#    author    : tristesire
#    date      : 18/03/2022
#
###########################################################################     

security:

    # custom user class, algorith is used for password hash, option: auto for auto select  
    encoders:
        App\Entity\User\User:
            algorithm: auto

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        # user is defined by property email
        app_user_provider:
            entity:
                class: App\Entity\User\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            lazy: true
            provider: app_user_provider
            guard:
                authenticators:
                    - App\Security\TokenAuthenticator
            logout:
                path: logout
                # where to redirect after logout
                target: homepage

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
         - { path: ^/admin, roles: ROLE_ADMIN }
         - { path: ^/member, roles: ROLE_MEMBER }
         - { path: ^/staff, roles: ROLE_STAFF  }
         - { path: ^/sadmin, roles: ROLE_SADMIN }
    
    # univertuel get 4 users : 
    # - member for a simple user
    # - staff to manage games and various content
    # - admin to manage the whole app
    # - sadmin whose are the app dev
        
    role_hierarchy:
        ROLE_STAFF : ROLE_MEMBER
        ROLE_ADMIN  : ROLE_WRITER
        ROLE_SADMIN : ROLE_ADMIN    
        
        
        
        
