<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20220530145408 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE campaign (id INT AUTO_INCREMENT NOT NULL, owner_id INT NOT NULL, game_id INT NOT NULL, name VARCHAR(120) NOT NULL, description TEXT NOT NULL, secret_code INT NOT NULL, INDEX IDX_1F1512DD7E3C61F9 (owner_id), INDEX IDX_1F1512DDE48FD905 (game_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE figure (id INT AUTO_INCREMENT NOT NULL, campaign_id INT NOT NULL, owner_id INT NOT NULL, figure INT NOT NULL, name VARCHAR(255) NOT NULL, INDEX IDX_2F57B37AF639F774 (campaign_id), INDEX IDX_2F57B37A7E3C61F9 (owner_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE game (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(100) NOT NULL, name VARCHAR(255) NOT NULL, image VARCHAR(255) DEFAULT NULL, description VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE message (id INT AUTO_INCREMENT NOT NULL, sender_id INT NOT NULL, receiver_id INT NOT NULL, thread_id INT NOT NULL, is_sender_readed TINYINT(1) NOT NULL, is_receiver_readed TINYINT(1) NOT NULL, number INT NOT NULL, date DATETIME NOT NULL, message LONGTEXT NOT NULL, INDEX IDX_B6BD307FF624B39D (sender_id), INDEX IDX_B6BD307FCD53EDB6 (receiver_id), INDEX IDX_B6BD307FE2904019 (thread_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE prophecy_advantage (id INT AUTO_INCREMENT NOT NULL, advantage_category_id INT NOT NULL, campaign_id INT DEFAULT NULL, name VARCHAR(120) NOT NULL, multiselect TINYINT(1) NOT NULL, buyable TINYINT(1) NOT NULL, initial_cost INT NOT NULL, description LONGTEXT NOT NULL, INDEX IDX_5E6FF7B63E248A36 (advantage_category_id), INDEX IDX_5E6FF7B6F639F774 (campaign_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE prophecy_advantage_category (id INT AUTO_INCREMENT NOT NULL, campaign_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, INDEX IDX_AD26AD6EF639F774 (campaign_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE prophecy_age (id INT AUTO_INCREMENT NOT NULL, campaign_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, start_att_value1 INT NOT NULL, start_att_value2 INT NOT NULL, start_att_value3 INT NOT NULL, start_att_value4 INT NOT NULL, INDEX IDX_44A3C1D3F639F774 (campaign_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE prophecy_armor (id INT AUTO_INCREMENT NOT NULL, category_id INT NOT NULL, campaign_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, weight INT NOT NULL, create_difficulty INT NOT NULL, construction_time INT NOT NULL, village_rarety VARCHAR(255) NOT NULL, city_rarety VARCHAR(255) NOT NULL, village_price INT NOT NULL, city_price INT NOT NULL, protection INT NOT NULL, move_penalty INT NOT NULL, material VARCHAR(255) NOT NULL, description LONGTEXT NOT NULL, INDEX IDX_3215A3CB12469DE2 (category_id), INDEX IDX_3215A3CBF639F774 (campaign_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE prophecy_armor_category (id INT AUTO_INCREMENT NOT NULL, campaign_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, INDEX IDX_4A883494F639F774 (campaign_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE prophecy_benefit (id INT AUTO_INCREMENT NOT NULL, caste_id INT NOT NULL, campaign_id INT DEFAULT NULL, name VARCHAR(120) NOT NULL, description LONGTEXT NOT NULL, INDEX IDX_D956005029B1D13 (caste_id), INDEX IDX_D9560050F639F774 (campaign_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE prophecy_caracteristic (id INT AUTO_INCREMENT NOT NULL, campaign_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, code VARCHAR(3) NOT NULL, min_value INT NOT NULL, maximum_value INT NOT NULL, xp_increase INT NOT NULL, description LONGTEXT NOT NULL, INDEX IDX_565B83D2F639F774 (campaign_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE prophecy_carrier (id INT AUTO_INCREMENT NOT NULL, campaign_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, caste VARCHAR(255) NOT NULL, prohibited VARCHAR(255) NOT NULL, min_status INT NOT NULL, technic VARCHAR(255) NOT NULL, INDEX IDX_C2E4F153F639F774 (campaign_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE prophecy_caste (id INT AUTO_INCREMENT NOT NULL, campaign_id INT DEFAULT NULL, name VARCHAR(50) NOT NULL, description LONGTEXT NOT NULL, INDEX IDX_3624C8FDF639F774 (campaign_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE prophecy_currency (id INT AUTO_INCREMENT NOT NULL, campaign_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, factor_value INT NOT NULL, available TINYINT(1) NOT NULL, display TINYINT(1) NOT NULL, code VARCHAR(255) NOT NULL, description LONGTEXT NOT NULL, INDEX IDX_8FB0093EF639F774 (campaign_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE prophecy_disadvantage (id INT AUTO_INCREMENT NOT NULL, advantage_category_id INT NOT NULL, campaign_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, multiselect TINYINT(1) NOT NULL, buyable TINYINT(1) NOT NULL, initial_cost INT NOT NULL, description LONGTEXT NOT NULL, INDEX IDX_B0E737C43E248A36 (advantage_category_id), INDEX IDX_B0E737C4F639F774 (campaign_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE prophecy_discipline (id INT AUTO_INCREMENT NOT NULL, campaign_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, min_value INT NOT NULL, maximum_value INT NOT NULL, description LONGTEXT NOT NULL, INDEX IDX_F61A8A2EF639F774 (campaign_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE prophecy_favour (id INT AUTO_INCREMENT NOT NULL, caste_id INT NOT NULL, campaign_id INT DEFAULT NULL, name VARCHAR(120) NOT NULL, description LONGTEXT NOT NULL, INDEX IDX_92916AB529B1D13 (caste_id), INDEX IDX_92916AB5F639F774 (campaign_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE prophecy_figure (id INT AUTO_INCREMENT NOT NULL, owner_id INT NOT NULL, campaign_id INT NOT NULL, caste_id INT DEFAULT NULL, omen_id INT DEFAULT NULL, age_id INT DEFAULT NULL, nation_id INT DEFAULT NULL, name VARCHAR(120) NOT NULL, mana INT DEFAULT NULL, reputation INT DEFAULT NULL, current_mana INT DEFAULT NULL, weight VARCHAR(255) DEFAULT NULL, size VARCHAR(255) DEFAULT NULL, xperience INT DEFAULT NULL, advantage_points INT DEFAULT NULL, background LONGTEXT DEFAULT NULL, is_finish TINYINT(1) NOT NULL, INDEX IDX_976724287E3C61F9 (owner_id), INDEX IDX_97672428F639F774 (campaign_id), INDEX IDX_9767242829B1D13 (caste_id), INDEX IDX_9767242847D39BD9 (omen_id), INDEX IDX_97672428CC80CD12 (age_id), INDEX IDX_97672428AE3899 (nation_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE prophecy_figures_weapons (figure_id INT NOT NULL, weapon_id INT NOT NULL, INDEX IDX_662476CC5C011B5 (figure_id), INDEX IDX_662476CC95B82273 (weapon_id), PRIMARY KEY(figure_id, weapon_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE prophecy_figures_armors (figure_id INT NOT NULL, armor_id INT NOT NULL, INDEX IDX_EBAE87AB5C011B5 (figure_id), INDEX IDX_EBAE87ABF5AA3663 (armor_id), PRIMARY KEY(figure_id, armor_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE prophecy_figures_shields (figure_id INT NOT NULL, shield_id INT NOT NULL, INDEX IDX_81EBFBBE5C011B5 (figure_id), INDEX IDX_81EBFBBE1BB82155 (shield_id), PRIMARY KEY(figure_id, shield_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE prophecy_figures_spells (figure_id INT NOT NULL, spell_id INT NOT NULL, INDEX IDX_CCC3DE325C011B5 (figure_id), INDEX IDX_CCC3DE32479EC90D (spell_id), PRIMARY KEY(figure_id, spell_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE prophecy_figures_advantages (figure_id INT NOT NULL, advantage_id INT NOT NULL, INDEX IDX_2F8C67065C011B5 (figure_id), INDEX IDX_2F8C67063864498A (advantage_id), PRIMARY KEY(figure_id, advantage_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE prophecy_figures_disadvantages (figure_id INT NOT NULL, disadvantage_id INT NOT NULL, INDEX IDX_C2316975C011B5 (figure_id), INDEX IDX_C2316977995CCA1 (disadvantage_id), PRIMARY KEY(figure_id, disadvantage_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE prophecy_figures_technics (figure_id INT NOT NULL, technic_id INT NOT NULL, INDEX IDX_ED5C7CFC5C011B5 (figure_id), INDEX IDX_ED5C7CFCFAAE137C (technic_id), PRIMARY KEY(figure_id, technic_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE prophecy_figures_favours (figure_id INT NOT NULL, favour_id INT NOT NULL, INDEX IDX_1160D4005C011B5 (figure_id), INDEX IDX_1160D400CA2F0FB1 (favour_id), PRIMARY KEY(figure_id, favour_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE prophecy_figures_benefits (figure_id INT NOT NULL, benefit_id INT NOT NULL, INDEX IDX_D3B13F465C011B5 (figure_id), INDEX IDX_D3B13F46B517B89 (benefit_id), PRIMARY KEY(figure_id, benefit_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE prophecy_figures_prohibiteds (figure_id INT NOT NULL, prohibited_id INT NOT NULL, INDEX IDX_CFD10BD25C011B5 (figure_id), INDEX IDX_CFD10BD2ECE85184 (prohibited_id), PRIMARY KEY(figure_id, prohibited_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE prophecy_figure_caracteristic (id INT AUTO_INCREMENT NOT NULL, figure_id INT NOT NULL, caracteristic_id INT DEFAULT NULL, value INT DEFAULT NULL, INDEX IDX_15D9E5B75C011B5 (figure_id), INDEX IDX_15D9E5B781194CF4 (caracteristic_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE prophecy_figure_currency (id INT AUTO_INCREMENT NOT NULL, figure_id INT NOT NULL, currency_id INT NOT NULL, value INT DEFAULT NULL, INDEX IDX_4DF1D5D85C011B5 (figure_id), INDEX IDX_4DF1D5D838248176 (currency_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE prophecy_figure_discipline (id INT AUTO_INCREMENT NOT NULL, discipline_id INT NOT NULL, figure_id INT NOT NULL, value INT DEFAULT NULL, mana INT DEFAULT NULL, current_mana INT DEFAULT NULL, INDEX IDX_715B82FAA5522701 (discipline_id), INDEX IDX_715B82FA5C011B5 (figure_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE prophecy_figure_major_attribute (id INT AUTO_INCREMENT NOT NULL, figure_id INT NOT NULL, major_attribute_id INT NOT NULL, value INT DEFAULT NULL, INDEX IDX_7F3920AB5C011B5 (figure_id), INDEX IDX_7F3920ABB4B49857 (major_attribute_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE prophecy_figure_minor_attribute (id INT AUTO_INCREMENT NOT NULL, figure_id INT NOT NULL, minor_attribute_id INT NOT NULL, value INT DEFAULT NULL, current_value INT DEFAULT NULL, INDEX IDX_8CD9540B5C011B5 (figure_id), INDEX IDX_8CD9540B86959B4E (minor_attribute_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE prophecy_figure_skill (id INT AUTO_INCREMENT NOT NULL, figure_id INT NOT NULL, skill_id INT NOT NULL, value INT DEFAULT NULL, INDEX IDX_551667BB5C011B5 (figure_id), INDEX IDX_551667BB5585C142 (skill_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE prophecy_figure_spell (id INT AUTO_INCREMENT NOT NULL, figure_id INT NOT NULL, spell_id INT NOT NULL, INDEX IDX_DB144E415C011B5 (figure_id), INDEX IDX_DB144E41479EC90D (spell_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE prophecy_figure_sphere (id INT AUTO_INCREMENT NOT NULL, figure_id INT NOT NULL, sphere_id INT NOT NULL, value INT DEFAULT NULL, mana INT DEFAULT NULL, current_mana INT DEFAULT NULL, INDEX IDX_C720C39F5C011B5 (figure_id), INDEX IDX_C720C39F75FD4EF9 (sphere_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE prophecy_figure_tendency (id INT AUTO_INCREMENT NOT NULL, figure_id INT NOT NULL, tendency_id INT NOT NULL, circles INT DEFAULT NULL, tendency_value INT DEFAULT NULL, INDEX IDX_C7E5D1E65C011B5 (figure_id), INDEX IDX_C7E5D1E66867581F (tendency_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE prophecy_figure_wound (id INT AUTO_INCREMENT NOT NULL, figure_id INT NOT NULL, wound_id INT NOT NULL, value INT DEFAULT NULL, INDEX IDX_625E6885C011B5 (figure_id), INDEX IDX_625E688EEE052C4 (wound_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE prophecy_major_attribute (id INT AUTO_INCREMENT NOT NULL, campaign_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, min_value INT NOT NULL, maximum_value INT NOT NULL, description LONGTEXT NOT NULL, INDEX IDX_C36238A6F639F774 (campaign_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE prophecy_minor_attribute (id INT AUTO_INCREMENT NOT NULL, campaign_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, min_value INT NOT NULL, maximum_value INT NOT NULL, description LONGTEXT NOT NULL, xp_increase INT NOT NULL, INDEX IDX_30824C06F639F774 (campaign_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE prophecy_nation (id INT AUTO_INCREMENT NOT NULL, campaign_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, available TINYINT(1) NOT NULL, display TINYINT(1) NOT NULL, description LONGTEXT NOT NULL, INDEX IDX_746AFA75F639F774 (campaign_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE prophecy_omen (id INT AUTO_INCREMENT NOT NULL, campaign_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, personnality VARCHAR(255) NOT NULL, motivation VARCHAR(255) NOT NULL, quality VARCHAR(255) NOT NULL, fault VARCHAR(255) NOT NULL, INDEX IDX_8ADE7198F639F774 (campaign_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE prophecy_prohibited (id INT AUTO_INCREMENT NOT NULL, caste_id INT NOT NULL, campaign_id INT DEFAULT NULL, name VARCHAR(70) NOT NULL, description LONGTEXT NOT NULL, INDEX IDX_722AEA2029B1D13 (caste_id), INDEX IDX_722AEA20F639F774 (campaign_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE prophecy_shield (id INT AUTO_INCREMENT NOT NULL, campaign_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, weight INT NOT NULL, create_difficulty INT NOT NULL, construction_time INT NOT NULL, village_rarety VARCHAR(255) NOT NULL, city_rarety VARCHAR(255) NOT NULL, village_price INT NOT NULL, city_price INT NOT NULL, protection INT NOT NULL, move_penalty INT NOT NULL, material VARCHAR(255) NOT NULL, description LONGTEXT NOT NULL, INDEX IDX_A6A345BAF639F774 (campaign_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE prophecy_skill (id INT AUTO_INCREMENT NOT NULL, skill_category_id INT DEFAULT NULL, campaign_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, xp_increase INT NOT NULL, cost INT NOT NULL, reserved TINYINT(1) NOT NULL, free TINYINT(1) NOT NULL, forbidden TINYINT(1) NOT NULL, maximum_value INT NOT NULL, min_value INT NOT NULL, available TINYINT(1) NOT NULL, display TINYINT(1) NOT NULL, description LONGTEXT NOT NULL, INDEX IDX_D30FB940AC58042E (skill_category_id), INDEX IDX_D30FB940F639F774 (campaign_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE prophecy_skill_category (id INT AUTO_INCREMENT NOT NULL, major_attribute_id INT NOT NULL, campaign_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, INDEX IDX_5D458C42B4B49857 (major_attribute_id), INDEX IDX_5D458C42F639F774 (campaign_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE prophecy_spell (id INT AUTO_INCREMENT NOT NULL, campaign_id INT DEFAULT NULL, sphere_id INT NOT NULL, discipline_id INT NOT NULL, name VARCHAR(255) NOT NULL, level INT NOT NULL, complexity INT NOT NULL, mana_cost INT NOT NULL, casting_time VARCHAR(255) NOT NULL, difficulty INT NOT NULL, description LONGTEXT NOT NULL, spell_keys VARCHAR(255) NOT NULL, INDEX IDX_5D0D90BAF639F774 (campaign_id), INDEX IDX_5D0D90BA75FD4EF9 (sphere_id), INDEX IDX_5D0D90BAA5522701 (discipline_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE prophecy_sphere (id INT AUTO_INCREMENT NOT NULL, campaign_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, maximum_value INT NOT NULL, min_value INT NOT NULL, xp_increase INT NOT NULL, description LONGTEXT NOT NULL, INDEX IDX_EDC9F1D5F639F774 (campaign_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE prophecy_start_caracteristic (id INT AUTO_INCREMENT NOT NULL, campaign_id INT DEFAULT NULL, value1 INT NOT NULL, value2 VARCHAR(255) NOT NULL, value3 INT NOT NULL, value4 INT NOT NULL, value5 INT NOT NULL, value6 INT NOT NULL, value7 INT NOT NULL, value8 INT NOT NULL, INDEX IDX_C251CB93F639F774 (campaign_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE prophecy_start_major_attribute (id INT AUTO_INCREMENT NOT NULL, campaign_id INT DEFAULT NULL, age_id INT NOT NULL, value1 INT NOT NULL, value2 INT NOT NULL, value3 INT NOT NULL, value4 INT NOT NULL, INDEX IDX_52071B4AF639F774 (campaign_id), INDEX IDX_52071B4ACC80CD12 (age_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE prophecy_start_skill (id INT AUTO_INCREMENT NOT NULL, campaign_id INT DEFAULT NULL, age_id INT DEFAULT NULL, value INT NOT NULL, INDEX IDX_415B7A10F639F774 (campaign_id), INDEX IDX_415B7A10CC80CD12 (age_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE prophecy_status (id INT AUTO_INCREMENT NOT NULL, caste_id INT NOT NULL, campaign_id INT DEFAULT NULL, name VARCHAR(50) NOT NULL, level INT NOT NULL, description TINYTEXT NOT NULL, INDEX IDX_C330F24E29B1D13 (caste_id), INDEX IDX_C330F24EF639F774 (campaign_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE prophecy_technic (id INT AUTO_INCREMENT NOT NULL, caste_id INT NOT NULL, campaign_id INT DEFAULT NULL, name VARCHAR(70) NOT NULL, description LONGTEXT NOT NULL, INDEX IDX_5A6261B729B1D13 (caste_id), INDEX IDX_5A6261B7F639F774 (campaign_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE prophecy_tendency (id INT AUTO_INCREMENT NOT NULL, campaign_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, max_circles INT NOT NULL, min_circles INT NOT NULL, min_value INT NOT NULL, maximum_value INT NOT NULL, description LONGTEXT NOT NULL, INDEX IDX_5A40D00F639F774 (campaign_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE prophecy_weapon (id INT AUTO_INCREMENT NOT NULL, carac_requirement1_id INT DEFAULT NULL, carac_requirement2_id INT DEFAULT NULL, campaign_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, weight INT NOT NULL, creation_difficulty INT NOT NULL, construction_delay INT NOT NULL, village_rarety VARCHAR(255) NOT NULL, city_rarety VARCHAR(255) NOT NULL, village_price INT NOT NULL, city_price INT NOT NULL, value_requirement1 INT DEFAULT NULL, value_requirement2 INT DEFAULT NULL, melee_initiative INT NOT NULL, contact_initiative INT NOT NULL, special VARCHAR(255) NOT NULL, damages VARCHAR(255) NOT NULL, description LONGTEXT NOT NULL, INDEX IDX_D10330B4BEDA033C (carac_requirement1_id), INDEX IDX_D10330B4AC6FACD2 (carac_requirement2_id), INDEX IDX_D10330B4F639F774 (campaign_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE prophecy_weapon_category (id INT AUTO_INCREMENT NOT NULL, campaign_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, INDEX IDX_50434B5AF639F774 (campaign_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE prophecy_wound (id INT AUTO_INCREMENT NOT NULL, campaign_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, damages VARCHAR(255) NOT NULL, max_wounds INT NOT NULL, malus INT NOT NULL, INDEX IDX_803C3873F639F774 (campaign_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE prophecy_xpincrease (id INT AUTO_INCREMENT NOT NULL, campaign_id INT DEFAULT NULL, caracteristic INT NOT NULL, major_attribute INT NOT NULL, minor_attribute INT NOT NULL, reserved_skill INT NOT NULL, skill INT NOT NULL, forbidden_skill INT NOT NULL, mana INT NOT NULL, spell INT NOT NULL, famous INT NOT NULL, favour INT NOT NULL, advantage INT NOT NULL, disadvantage INT NOT NULL, INDEX IDX_106B5169F639F774 (campaign_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE thread (id INT AUTO_INCREMENT NOT NULL, sender_id INT NOT NULL, receiver_id INT NOT NULL, is_receiver_deleted TINYINT(1) NOT NULL, is_sender_deleted TINYINT(1) NOT NULL, purpose VARCHAR(255) NOT NULL, INDEX IDX_31204C83F624B39D (sender_id), INDEX IDX_31204C83CD53EDB6 (receiver_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user (id INT AUTO_INCREMENT NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, is_active TINYINT(1) NOT NULL, username VARCHAR(30) NOT NULL, avatar VARCHAR(180) DEFAULT NULL, description LONGTEXT NOT NULL, UNIQUE INDEX UNIQ_8D93D649E7927C74 (email), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user_relations (user_id INT NOT NULL, relation INT NOT NULL, INDEX IDX_148C329CA76ED395 (user_id), INDEX IDX_148C329C62894749 (relation), PRIMARY KEY(user_id, relation)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE campaign ADD CONSTRAINT FK_1F1512DD7E3C61F9 FOREIGN KEY (owner_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE campaign ADD CONSTRAINT FK_1F1512DDE48FD905 FOREIGN KEY (game_id) REFERENCES game (id)');
        $this->addSql('ALTER TABLE figure ADD CONSTRAINT FK_2F57B37AF639F774 FOREIGN KEY (campaign_id) REFERENCES campaign (id)');
        $this->addSql('ALTER TABLE figure ADD CONSTRAINT FK_2F57B37A7E3C61F9 FOREIGN KEY (owner_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307FF624B39D FOREIGN KEY (sender_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307FCD53EDB6 FOREIGN KEY (receiver_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307FE2904019 FOREIGN KEY (thread_id) REFERENCES thread (id)');
        $this->addSql('ALTER TABLE prophecy_advantage ADD CONSTRAINT FK_5E6FF7B63E248A36 FOREIGN KEY (advantage_category_id) REFERENCES prophecy_advantage_category (id)');
        $this->addSql('ALTER TABLE prophecy_advantage ADD CONSTRAINT FK_5E6FF7B6F639F774 FOREIGN KEY (campaign_id) REFERENCES campaign (id)');
        $this->addSql('ALTER TABLE prophecy_advantage_category ADD CONSTRAINT FK_AD26AD6EF639F774 FOREIGN KEY (campaign_id) REFERENCES campaign (id)');
        $this->addSql('ALTER TABLE prophecy_age ADD CONSTRAINT FK_44A3C1D3F639F774 FOREIGN KEY (campaign_id) REFERENCES campaign (id)');
        $this->addSql('ALTER TABLE prophecy_armor ADD CONSTRAINT FK_3215A3CB12469DE2 FOREIGN KEY (category_id) REFERENCES prophecy_armor_category (id)');
        $this->addSql('ALTER TABLE prophecy_armor ADD CONSTRAINT FK_3215A3CBF639F774 FOREIGN KEY (campaign_id) REFERENCES campaign (id)');
        $this->addSql('ALTER TABLE prophecy_armor_category ADD CONSTRAINT FK_4A883494F639F774 FOREIGN KEY (campaign_id) REFERENCES campaign (id)');
        $this->addSql('ALTER TABLE prophecy_benefit ADD CONSTRAINT FK_D956005029B1D13 FOREIGN KEY (caste_id) REFERENCES prophecy_caste (id)');
        $this->addSql('ALTER TABLE prophecy_benefit ADD CONSTRAINT FK_D9560050F639F774 FOREIGN KEY (campaign_id) REFERENCES campaign (id)');
        $this->addSql('ALTER TABLE prophecy_caracteristic ADD CONSTRAINT FK_565B83D2F639F774 FOREIGN KEY (campaign_id) REFERENCES campaign (id)');
        $this->addSql('ALTER TABLE prophecy_carrier ADD CONSTRAINT FK_C2E4F153F639F774 FOREIGN KEY (campaign_id) REFERENCES campaign (id)');
        $this->addSql('ALTER TABLE prophecy_caste ADD CONSTRAINT FK_3624C8FDF639F774 FOREIGN KEY (campaign_id) REFERENCES campaign (id)');
        $this->addSql('ALTER TABLE prophecy_currency ADD CONSTRAINT FK_8FB0093EF639F774 FOREIGN KEY (campaign_id) REFERENCES campaign (id)');
        $this->addSql('ALTER TABLE prophecy_disadvantage ADD CONSTRAINT FK_B0E737C43E248A36 FOREIGN KEY (advantage_category_id) REFERENCES prophecy_advantage_category (id)');
        $this->addSql('ALTER TABLE prophecy_disadvantage ADD CONSTRAINT FK_B0E737C4F639F774 FOREIGN KEY (campaign_id) REFERENCES campaign (id)');
        $this->addSql('ALTER TABLE prophecy_discipline ADD CONSTRAINT FK_F61A8A2EF639F774 FOREIGN KEY (campaign_id) REFERENCES campaign (id)');
        $this->addSql('ALTER TABLE prophecy_favour ADD CONSTRAINT FK_92916AB529B1D13 FOREIGN KEY (caste_id) REFERENCES prophecy_caste (id)');
        $this->addSql('ALTER TABLE prophecy_favour ADD CONSTRAINT FK_92916AB5F639F774 FOREIGN KEY (campaign_id) REFERENCES campaign (id)');
        $this->addSql('ALTER TABLE prophecy_figure ADD CONSTRAINT FK_976724287E3C61F9 FOREIGN KEY (owner_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE prophecy_figure ADD CONSTRAINT FK_97672428F639F774 FOREIGN KEY (campaign_id) REFERENCES campaign (id)');
        $this->addSql('ALTER TABLE prophecy_figure ADD CONSTRAINT FK_9767242829B1D13 FOREIGN KEY (caste_id) REFERENCES prophecy_caste (id)');
        $this->addSql('ALTER TABLE prophecy_figure ADD CONSTRAINT FK_9767242847D39BD9 FOREIGN KEY (omen_id) REFERENCES prophecy_omen (id)');
        $this->addSql('ALTER TABLE prophecy_figure ADD CONSTRAINT FK_97672428CC80CD12 FOREIGN KEY (age_id) REFERENCES prophecy_age (id)');
        $this->addSql('ALTER TABLE prophecy_figure ADD CONSTRAINT FK_97672428AE3899 FOREIGN KEY (nation_id) REFERENCES prophecy_nation (id)');
        $this->addSql('ALTER TABLE prophecy_figures_weapons ADD CONSTRAINT FK_662476CC5C011B5 FOREIGN KEY (figure_id) REFERENCES prophecy_figure (id)');
        $this->addSql('ALTER TABLE prophecy_figures_weapons ADD CONSTRAINT FK_662476CC95B82273 FOREIGN KEY (weapon_id) REFERENCES prophecy_weapon (id)');
        $this->addSql('ALTER TABLE prophecy_figures_armors ADD CONSTRAINT FK_EBAE87AB5C011B5 FOREIGN KEY (figure_id) REFERENCES prophecy_figure (id)');
        $this->addSql('ALTER TABLE prophecy_figures_armors ADD CONSTRAINT FK_EBAE87ABF5AA3663 FOREIGN KEY (armor_id) REFERENCES prophecy_armor (id)');
        $this->addSql('ALTER TABLE prophecy_figures_shields ADD CONSTRAINT FK_81EBFBBE5C011B5 FOREIGN KEY (figure_id) REFERENCES prophecy_figure (id)');
        $this->addSql('ALTER TABLE prophecy_figures_shields ADD CONSTRAINT FK_81EBFBBE1BB82155 FOREIGN KEY (shield_id) REFERENCES prophecy_shield (id)');
        $this->addSql('ALTER TABLE prophecy_figures_spells ADD CONSTRAINT FK_CCC3DE325C011B5 FOREIGN KEY (figure_id) REFERENCES prophecy_figure (id)');
        $this->addSql('ALTER TABLE prophecy_figures_spells ADD CONSTRAINT FK_CCC3DE32479EC90D FOREIGN KEY (spell_id) REFERENCES prophecy_spell (id)');
        $this->addSql('ALTER TABLE prophecy_figures_advantages ADD CONSTRAINT FK_2F8C67065C011B5 FOREIGN KEY (figure_id) REFERENCES prophecy_figure (id)');
        $this->addSql('ALTER TABLE prophecy_figures_advantages ADD CONSTRAINT FK_2F8C67063864498A FOREIGN KEY (advantage_id) REFERENCES prophecy_advantage (id)');
        $this->addSql('ALTER TABLE prophecy_figures_disadvantages ADD CONSTRAINT FK_C2316975C011B5 FOREIGN KEY (figure_id) REFERENCES prophecy_figure (id)');
        $this->addSql('ALTER TABLE prophecy_figures_disadvantages ADD CONSTRAINT FK_C2316977995CCA1 FOREIGN KEY (disadvantage_id) REFERENCES prophecy_disadvantage (id)');
        $this->addSql('ALTER TABLE prophecy_figures_technics ADD CONSTRAINT FK_ED5C7CFC5C011B5 FOREIGN KEY (figure_id) REFERENCES prophecy_figure (id)');
        $this->addSql('ALTER TABLE prophecy_figures_technics ADD CONSTRAINT FK_ED5C7CFCFAAE137C FOREIGN KEY (technic_id) REFERENCES prophecy_technic (id)');
        $this->addSql('ALTER TABLE prophecy_figures_favours ADD CONSTRAINT FK_1160D4005C011B5 FOREIGN KEY (figure_id) REFERENCES prophecy_figure (id)');
        $this->addSql('ALTER TABLE prophecy_figures_favours ADD CONSTRAINT FK_1160D400CA2F0FB1 FOREIGN KEY (favour_id) REFERENCES prophecy_favour (id)');
        $this->addSql('ALTER TABLE prophecy_figures_benefits ADD CONSTRAINT FK_D3B13F465C011B5 FOREIGN KEY (figure_id) REFERENCES prophecy_figure (id)');
        $this->addSql('ALTER TABLE prophecy_figures_benefits ADD CONSTRAINT FK_D3B13F46B517B89 FOREIGN KEY (benefit_id) REFERENCES prophecy_benefit (id)');
        $this->addSql('ALTER TABLE prophecy_figures_prohibiteds ADD CONSTRAINT FK_CFD10BD25C011B5 FOREIGN KEY (figure_id) REFERENCES prophecy_figure (id)');
        $this->addSql('ALTER TABLE prophecy_figures_prohibiteds ADD CONSTRAINT FK_CFD10BD2ECE85184 FOREIGN KEY (prohibited_id) REFERENCES prophecy_prohibited (id)');
        $this->addSql('ALTER TABLE prophecy_figure_caracteristic ADD CONSTRAINT FK_15D9E5B75C011B5 FOREIGN KEY (figure_id) REFERENCES prophecy_figure (id)');
        $this->addSql('ALTER TABLE prophecy_figure_caracteristic ADD CONSTRAINT FK_15D9E5B781194CF4 FOREIGN KEY (caracteristic_id) REFERENCES prophecy_caracteristic (id)');
        $this->addSql('ALTER TABLE prophecy_figure_currency ADD CONSTRAINT FK_4DF1D5D85C011B5 FOREIGN KEY (figure_id) REFERENCES prophecy_figure (id)');
        $this->addSql('ALTER TABLE prophecy_figure_currency ADD CONSTRAINT FK_4DF1D5D838248176 FOREIGN KEY (currency_id) REFERENCES prophecy_currency (id)');
        $this->addSql('ALTER TABLE prophecy_figure_discipline ADD CONSTRAINT FK_715B82FAA5522701 FOREIGN KEY (discipline_id) REFERENCES prophecy_discipline (id)');
        $this->addSql('ALTER TABLE prophecy_figure_discipline ADD CONSTRAINT FK_715B82FA5C011B5 FOREIGN KEY (figure_id) REFERENCES prophecy_figure (id)');
        $this->addSql('ALTER TABLE prophecy_figure_major_attribute ADD CONSTRAINT FK_7F3920AB5C011B5 FOREIGN KEY (figure_id) REFERENCES prophecy_figure (id)');
        $this->addSql('ALTER TABLE prophecy_figure_major_attribute ADD CONSTRAINT FK_7F3920ABB4B49857 FOREIGN KEY (major_attribute_id) REFERENCES prophecy_major_attribute (id)');
        $this->addSql('ALTER TABLE prophecy_figure_minor_attribute ADD CONSTRAINT FK_8CD9540B5C011B5 FOREIGN KEY (figure_id) REFERENCES prophecy_figure (id)');
        $this->addSql('ALTER TABLE prophecy_figure_minor_attribute ADD CONSTRAINT FK_8CD9540B86959B4E FOREIGN KEY (minor_attribute_id) REFERENCES prophecy_minor_attribute (id)');
        $this->addSql('ALTER TABLE prophecy_figure_skill ADD CONSTRAINT FK_551667BB5C011B5 FOREIGN KEY (figure_id) REFERENCES prophecy_figure (id)');
        $this->addSql('ALTER TABLE prophecy_figure_skill ADD CONSTRAINT FK_551667BB5585C142 FOREIGN KEY (skill_id) REFERENCES prophecy_skill (id)');
        $this->addSql('ALTER TABLE prophecy_figure_spell ADD CONSTRAINT FK_DB144E415C011B5 FOREIGN KEY (figure_id) REFERENCES prophecy_figure (id)');
        $this->addSql('ALTER TABLE prophecy_figure_spell ADD CONSTRAINT FK_DB144E41479EC90D FOREIGN KEY (spell_id) REFERENCES prophecy_spell (id)');
        $this->addSql('ALTER TABLE prophecy_figure_sphere ADD CONSTRAINT FK_C720C39F5C011B5 FOREIGN KEY (figure_id) REFERENCES prophecy_figure (id)');
        $this->addSql('ALTER TABLE prophecy_figure_sphere ADD CONSTRAINT FK_C720C39F75FD4EF9 FOREIGN KEY (sphere_id) REFERENCES prophecy_sphere (id)');
        $this->addSql('ALTER TABLE prophecy_figure_tendency ADD CONSTRAINT FK_C7E5D1E65C011B5 FOREIGN KEY (figure_id) REFERENCES prophecy_figure (id)');
        $this->addSql('ALTER TABLE prophecy_figure_tendency ADD CONSTRAINT FK_C7E5D1E66867581F FOREIGN KEY (tendency_id) REFERENCES prophecy_tendency (id)');
        $this->addSql('ALTER TABLE prophecy_figure_wound ADD CONSTRAINT FK_625E6885C011B5 FOREIGN KEY (figure_id) REFERENCES prophecy_figure (id)');
        $this->addSql('ALTER TABLE prophecy_figure_wound ADD CONSTRAINT FK_625E688EEE052C4 FOREIGN KEY (wound_id) REFERENCES prophecy_wound (id)');
        $this->addSql('ALTER TABLE prophecy_major_attribute ADD CONSTRAINT FK_C36238A6F639F774 FOREIGN KEY (campaign_id) REFERENCES campaign (id)');
        $this->addSql('ALTER TABLE prophecy_minor_attribute ADD CONSTRAINT FK_30824C06F639F774 FOREIGN KEY (campaign_id) REFERENCES campaign (id)');
        $this->addSql('ALTER TABLE prophecy_nation ADD CONSTRAINT FK_746AFA75F639F774 FOREIGN KEY (campaign_id) REFERENCES campaign (id)');
        $this->addSql('ALTER TABLE prophecy_omen ADD CONSTRAINT FK_8ADE7198F639F774 FOREIGN KEY (campaign_id) REFERENCES campaign (id)');
        $this->addSql('ALTER TABLE prophecy_prohibited ADD CONSTRAINT FK_722AEA2029B1D13 FOREIGN KEY (caste_id) REFERENCES prophecy_caste (id)');
        $this->addSql('ALTER TABLE prophecy_prohibited ADD CONSTRAINT FK_722AEA20F639F774 FOREIGN KEY (campaign_id) REFERENCES campaign (id)');
        $this->addSql('ALTER TABLE prophecy_shield ADD CONSTRAINT FK_A6A345BAF639F774 FOREIGN KEY (campaign_id) REFERENCES campaign (id)');
        $this->addSql('ALTER TABLE prophecy_skill ADD CONSTRAINT FK_D30FB940AC58042E FOREIGN KEY (skill_category_id) REFERENCES prophecy_skill_category (id)');
        $this->addSql('ALTER TABLE prophecy_skill ADD CONSTRAINT FK_D30FB940F639F774 FOREIGN KEY (campaign_id) REFERENCES campaign (id)');
        $this->addSql('ALTER TABLE prophecy_skill_category ADD CONSTRAINT FK_5D458C42B4B49857 FOREIGN KEY (major_attribute_id) REFERENCES prophecy_major_attribute (id)');
        $this->addSql('ALTER TABLE prophecy_skill_category ADD CONSTRAINT FK_5D458C42F639F774 FOREIGN KEY (campaign_id) REFERENCES campaign (id)');
        $this->addSql('ALTER TABLE prophecy_spell ADD CONSTRAINT FK_5D0D90BAF639F774 FOREIGN KEY (campaign_id) REFERENCES campaign (id)');
        $this->addSql('ALTER TABLE prophecy_spell ADD CONSTRAINT FK_5D0D90BA75FD4EF9 FOREIGN KEY (sphere_id) REFERENCES prophecy_sphere (id)');
        $this->addSql('ALTER TABLE prophecy_spell ADD CONSTRAINT FK_5D0D90BAA5522701 FOREIGN KEY (discipline_id) REFERENCES prophecy_discipline (id)');
        $this->addSql('ALTER TABLE prophecy_sphere ADD CONSTRAINT FK_EDC9F1D5F639F774 FOREIGN KEY (campaign_id) REFERENCES campaign (id)');
        $this->addSql('ALTER TABLE prophecy_start_caracteristic ADD CONSTRAINT FK_C251CB93F639F774 FOREIGN KEY (campaign_id) REFERENCES campaign (id)');
        $this->addSql('ALTER TABLE prophecy_start_major_attribute ADD CONSTRAINT FK_52071B4AF639F774 FOREIGN KEY (campaign_id) REFERENCES campaign (id)');
        $this->addSql('ALTER TABLE prophecy_start_major_attribute ADD CONSTRAINT FK_52071B4ACC80CD12 FOREIGN KEY (age_id) REFERENCES prophecy_age (id)');
        $this->addSql('ALTER TABLE prophecy_start_skill ADD CONSTRAINT FK_415B7A10F639F774 FOREIGN KEY (campaign_id) REFERENCES campaign (id)');
        $this->addSql('ALTER TABLE prophecy_start_skill ADD CONSTRAINT FK_415B7A10CC80CD12 FOREIGN KEY (age_id) REFERENCES prophecy_age (id)');
        $this->addSql('ALTER TABLE prophecy_status ADD CONSTRAINT FK_C330F24E29B1D13 FOREIGN KEY (caste_id) REFERENCES prophecy_caste (id)');
        $this->addSql('ALTER TABLE prophecy_status ADD CONSTRAINT FK_C330F24EF639F774 FOREIGN KEY (campaign_id) REFERENCES campaign (id)');
        $this->addSql('ALTER TABLE prophecy_technic ADD CONSTRAINT FK_5A6261B729B1D13 FOREIGN KEY (caste_id) REFERENCES prophecy_caste (id)');
        $this->addSql('ALTER TABLE prophecy_technic ADD CONSTRAINT FK_5A6261B7F639F774 FOREIGN KEY (campaign_id) REFERENCES campaign (id)');
        $this->addSql('ALTER TABLE prophecy_tendency ADD CONSTRAINT FK_5A40D00F639F774 FOREIGN KEY (campaign_id) REFERENCES campaign (id)');
        $this->addSql('ALTER TABLE prophecy_weapon ADD CONSTRAINT FK_D10330B4BEDA033C FOREIGN KEY (carac_requirement1_id) REFERENCES prophecy_caracteristic (id)');
        $this->addSql('ALTER TABLE prophecy_weapon ADD CONSTRAINT FK_D10330B4AC6FACD2 FOREIGN KEY (carac_requirement2_id) REFERENCES prophecy_caracteristic (id)');
        $this->addSql('ALTER TABLE prophecy_weapon ADD CONSTRAINT FK_D10330B4F639F774 FOREIGN KEY (campaign_id) REFERENCES campaign (id)');
        $this->addSql('ALTER TABLE prophecy_weapon_category ADD CONSTRAINT FK_50434B5AF639F774 FOREIGN KEY (campaign_id) REFERENCES campaign (id)');
        $this->addSql('ALTER TABLE prophecy_wound ADD CONSTRAINT FK_803C3873F639F774 FOREIGN KEY (campaign_id) REFERENCES campaign (id)');
        $this->addSql('ALTER TABLE prophecy_xpincrease ADD CONSTRAINT FK_106B5169F639F774 FOREIGN KEY (campaign_id) REFERENCES campaign (id)');
        $this->addSql('ALTER TABLE thread ADD CONSTRAINT FK_31204C83F624B39D FOREIGN KEY (sender_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE thread ADD CONSTRAINT FK_31204C83CD53EDB6 FOREIGN KEY (receiver_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE user_relations ADD CONSTRAINT FK_148C329CA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE user_relations ADD CONSTRAINT FK_148C329C62894749 FOREIGN KEY (relation) REFERENCES user (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE figure DROP FOREIGN KEY FK_2F57B37AF639F774');
        $this->addSql('ALTER TABLE prophecy_advantage DROP FOREIGN KEY FK_5E6FF7B6F639F774');
        $this->addSql('ALTER TABLE prophecy_advantage_category DROP FOREIGN KEY FK_AD26AD6EF639F774');
        $this->addSql('ALTER TABLE prophecy_age DROP FOREIGN KEY FK_44A3C1D3F639F774');
        $this->addSql('ALTER TABLE prophecy_armor DROP FOREIGN KEY FK_3215A3CBF639F774');
        $this->addSql('ALTER TABLE prophecy_armor_category DROP FOREIGN KEY FK_4A883494F639F774');
        $this->addSql('ALTER TABLE prophecy_benefit DROP FOREIGN KEY FK_D9560050F639F774');
        $this->addSql('ALTER TABLE prophecy_caracteristic DROP FOREIGN KEY FK_565B83D2F639F774');
        $this->addSql('ALTER TABLE prophecy_carrier DROP FOREIGN KEY FK_C2E4F153F639F774');
        $this->addSql('ALTER TABLE prophecy_caste DROP FOREIGN KEY FK_3624C8FDF639F774');
        $this->addSql('ALTER TABLE prophecy_currency DROP FOREIGN KEY FK_8FB0093EF639F774');
        $this->addSql('ALTER TABLE prophecy_disadvantage DROP FOREIGN KEY FK_B0E737C4F639F774');
        $this->addSql('ALTER TABLE prophecy_discipline DROP FOREIGN KEY FK_F61A8A2EF639F774');
        $this->addSql('ALTER TABLE prophecy_favour DROP FOREIGN KEY FK_92916AB5F639F774');
        $this->addSql('ALTER TABLE prophecy_figure DROP FOREIGN KEY FK_97672428F639F774');
        $this->addSql('ALTER TABLE prophecy_major_attribute DROP FOREIGN KEY FK_C36238A6F639F774');
        $this->addSql('ALTER TABLE prophecy_minor_attribute DROP FOREIGN KEY FK_30824C06F639F774');
        $this->addSql('ALTER TABLE prophecy_nation DROP FOREIGN KEY FK_746AFA75F639F774');
        $this->addSql('ALTER TABLE prophecy_omen DROP FOREIGN KEY FK_8ADE7198F639F774');
        $this->addSql('ALTER TABLE prophecy_prohibited DROP FOREIGN KEY FK_722AEA20F639F774');
        $this->addSql('ALTER TABLE prophecy_shield DROP FOREIGN KEY FK_A6A345BAF639F774');
        $this->addSql('ALTER TABLE prophecy_skill DROP FOREIGN KEY FK_D30FB940F639F774');
        $this->addSql('ALTER TABLE prophecy_skill_category DROP FOREIGN KEY FK_5D458C42F639F774');
        $this->addSql('ALTER TABLE prophecy_spell DROP FOREIGN KEY FK_5D0D90BAF639F774');
        $this->addSql('ALTER TABLE prophecy_sphere DROP FOREIGN KEY FK_EDC9F1D5F639F774');
        $this->addSql('ALTER TABLE prophecy_start_caracteristic DROP FOREIGN KEY FK_C251CB93F639F774');
        $this->addSql('ALTER TABLE prophecy_start_major_attribute DROP FOREIGN KEY FK_52071B4AF639F774');
        $this->addSql('ALTER TABLE prophecy_start_skill DROP FOREIGN KEY FK_415B7A10F639F774');
        $this->addSql('ALTER TABLE prophecy_status DROP FOREIGN KEY FK_C330F24EF639F774');
        $this->addSql('ALTER TABLE prophecy_technic DROP FOREIGN KEY FK_5A6261B7F639F774');
        $this->addSql('ALTER TABLE prophecy_tendency DROP FOREIGN KEY FK_5A40D00F639F774');
        $this->addSql('ALTER TABLE prophecy_weapon DROP FOREIGN KEY FK_D10330B4F639F774');
        $this->addSql('ALTER TABLE prophecy_weapon_category DROP FOREIGN KEY FK_50434B5AF639F774');
        $this->addSql('ALTER TABLE prophecy_wound DROP FOREIGN KEY FK_803C3873F639F774');
        $this->addSql('ALTER TABLE prophecy_xpincrease DROP FOREIGN KEY FK_106B5169F639F774');
        $this->addSql('ALTER TABLE campaign DROP FOREIGN KEY FK_1F1512DDE48FD905');
        $this->addSql('ALTER TABLE prophecy_figures_advantages DROP FOREIGN KEY FK_2F8C67063864498A');
        $this->addSql('ALTER TABLE prophecy_advantage DROP FOREIGN KEY FK_5E6FF7B63E248A36');
        $this->addSql('ALTER TABLE prophecy_disadvantage DROP FOREIGN KEY FK_B0E737C43E248A36');
        $this->addSql('ALTER TABLE prophecy_figure DROP FOREIGN KEY FK_97672428CC80CD12');
        $this->addSql('ALTER TABLE prophecy_start_major_attribute DROP FOREIGN KEY FK_52071B4ACC80CD12');
        $this->addSql('ALTER TABLE prophecy_start_skill DROP FOREIGN KEY FK_415B7A10CC80CD12');
        $this->addSql('ALTER TABLE prophecy_figures_armors DROP FOREIGN KEY FK_EBAE87ABF5AA3663');
        $this->addSql('ALTER TABLE prophecy_armor DROP FOREIGN KEY FK_3215A3CB12469DE2');
        $this->addSql('ALTER TABLE prophecy_figures_benefits DROP FOREIGN KEY FK_D3B13F46B517B89');
        $this->addSql('ALTER TABLE prophecy_figure_caracteristic DROP FOREIGN KEY FK_15D9E5B781194CF4');
        $this->addSql('ALTER TABLE prophecy_weapon DROP FOREIGN KEY FK_D10330B4BEDA033C');
        $this->addSql('ALTER TABLE prophecy_weapon DROP FOREIGN KEY FK_D10330B4AC6FACD2');
        $this->addSql('ALTER TABLE prophecy_benefit DROP FOREIGN KEY FK_D956005029B1D13');
        $this->addSql('ALTER TABLE prophecy_favour DROP FOREIGN KEY FK_92916AB529B1D13');
        $this->addSql('ALTER TABLE prophecy_figure DROP FOREIGN KEY FK_9767242829B1D13');
        $this->addSql('ALTER TABLE prophecy_prohibited DROP FOREIGN KEY FK_722AEA2029B1D13');
        $this->addSql('ALTER TABLE prophecy_status DROP FOREIGN KEY FK_C330F24E29B1D13');
        $this->addSql('ALTER TABLE prophecy_technic DROP FOREIGN KEY FK_5A6261B729B1D13');
        $this->addSql('ALTER TABLE prophecy_figure_currency DROP FOREIGN KEY FK_4DF1D5D838248176');
        $this->addSql('ALTER TABLE prophecy_figures_disadvantages DROP FOREIGN KEY FK_C2316977995CCA1');
        $this->addSql('ALTER TABLE prophecy_figure_discipline DROP FOREIGN KEY FK_715B82FAA5522701');
        $this->addSql('ALTER TABLE prophecy_spell DROP FOREIGN KEY FK_5D0D90BAA5522701');
        $this->addSql('ALTER TABLE prophecy_figures_favours DROP FOREIGN KEY FK_1160D400CA2F0FB1');
        $this->addSql('ALTER TABLE prophecy_figures_weapons DROP FOREIGN KEY FK_662476CC5C011B5');
        $this->addSql('ALTER TABLE prophecy_figures_armors DROP FOREIGN KEY FK_EBAE87AB5C011B5');
        $this->addSql('ALTER TABLE prophecy_figures_shields DROP FOREIGN KEY FK_81EBFBBE5C011B5');
        $this->addSql('ALTER TABLE prophecy_figures_spells DROP FOREIGN KEY FK_CCC3DE325C011B5');
        $this->addSql('ALTER TABLE prophecy_figures_advantages DROP FOREIGN KEY FK_2F8C67065C011B5');
        $this->addSql('ALTER TABLE prophecy_figures_disadvantages DROP FOREIGN KEY FK_C2316975C011B5');
        $this->addSql('ALTER TABLE prophecy_figures_technics DROP FOREIGN KEY FK_ED5C7CFC5C011B5');
        $this->addSql('ALTER TABLE prophecy_figures_favours DROP FOREIGN KEY FK_1160D4005C011B5');
        $this->addSql('ALTER TABLE prophecy_figures_benefits DROP FOREIGN KEY FK_D3B13F465C011B5');
        $this->addSql('ALTER TABLE prophecy_figures_prohibiteds DROP FOREIGN KEY FK_CFD10BD25C011B5');
        $this->addSql('ALTER TABLE prophecy_figure_caracteristic DROP FOREIGN KEY FK_15D9E5B75C011B5');
        $this->addSql('ALTER TABLE prophecy_figure_currency DROP FOREIGN KEY FK_4DF1D5D85C011B5');
        $this->addSql('ALTER TABLE prophecy_figure_discipline DROP FOREIGN KEY FK_715B82FA5C011B5');
        $this->addSql('ALTER TABLE prophecy_figure_major_attribute DROP FOREIGN KEY FK_7F3920AB5C011B5');
        $this->addSql('ALTER TABLE prophecy_figure_minor_attribute DROP FOREIGN KEY FK_8CD9540B5C011B5');
        $this->addSql('ALTER TABLE prophecy_figure_skill DROP FOREIGN KEY FK_551667BB5C011B5');
        $this->addSql('ALTER TABLE prophecy_figure_spell DROP FOREIGN KEY FK_DB144E415C011B5');
        $this->addSql('ALTER TABLE prophecy_figure_sphere DROP FOREIGN KEY FK_C720C39F5C011B5');
        $this->addSql('ALTER TABLE prophecy_figure_tendency DROP FOREIGN KEY FK_C7E5D1E65C011B5');
        $this->addSql('ALTER TABLE prophecy_figure_wound DROP FOREIGN KEY FK_625E6885C011B5');
        $this->addSql('ALTER TABLE prophecy_figure_major_attribute DROP FOREIGN KEY FK_7F3920ABB4B49857');
        $this->addSql('ALTER TABLE prophecy_skill_category DROP FOREIGN KEY FK_5D458C42B4B49857');
        $this->addSql('ALTER TABLE prophecy_figure_minor_attribute DROP FOREIGN KEY FK_8CD9540B86959B4E');
        $this->addSql('ALTER TABLE prophecy_figure DROP FOREIGN KEY FK_97672428AE3899');
        $this->addSql('ALTER TABLE prophecy_figure DROP FOREIGN KEY FK_9767242847D39BD9');
        $this->addSql('ALTER TABLE prophecy_figures_prohibiteds DROP FOREIGN KEY FK_CFD10BD2ECE85184');
        $this->addSql('ALTER TABLE prophecy_figures_shields DROP FOREIGN KEY FK_81EBFBBE1BB82155');
        $this->addSql('ALTER TABLE prophecy_figure_skill DROP FOREIGN KEY FK_551667BB5585C142');
        $this->addSql('ALTER TABLE prophecy_skill DROP FOREIGN KEY FK_D30FB940AC58042E');
        $this->addSql('ALTER TABLE prophecy_figures_spells DROP FOREIGN KEY FK_CCC3DE32479EC90D');
        $this->addSql('ALTER TABLE prophecy_figure_spell DROP FOREIGN KEY FK_DB144E41479EC90D');
        $this->addSql('ALTER TABLE prophecy_figure_sphere DROP FOREIGN KEY FK_C720C39F75FD4EF9');
        $this->addSql('ALTER TABLE prophecy_spell DROP FOREIGN KEY FK_5D0D90BA75FD4EF9');
        $this->addSql('ALTER TABLE prophecy_figures_technics DROP FOREIGN KEY FK_ED5C7CFCFAAE137C');
        $this->addSql('ALTER TABLE prophecy_figure_tendency DROP FOREIGN KEY FK_C7E5D1E66867581F');
        $this->addSql('ALTER TABLE prophecy_figures_weapons DROP FOREIGN KEY FK_662476CC95B82273');
        $this->addSql('ALTER TABLE prophecy_figure_wound DROP FOREIGN KEY FK_625E688EEE052C4');
        $this->addSql('ALTER TABLE message DROP FOREIGN KEY FK_B6BD307FE2904019');
        $this->addSql('ALTER TABLE campaign DROP FOREIGN KEY FK_1F1512DD7E3C61F9');
        $this->addSql('ALTER TABLE figure DROP FOREIGN KEY FK_2F57B37A7E3C61F9');
        $this->addSql('ALTER TABLE message DROP FOREIGN KEY FK_B6BD307FF624B39D');
        $this->addSql('ALTER TABLE message DROP FOREIGN KEY FK_B6BD307FCD53EDB6');
        $this->addSql('ALTER TABLE prophecy_figure DROP FOREIGN KEY FK_976724287E3C61F9');
        $this->addSql('ALTER TABLE thread DROP FOREIGN KEY FK_31204C83F624B39D');
        $this->addSql('ALTER TABLE thread DROP FOREIGN KEY FK_31204C83CD53EDB6');
        $this->addSql('ALTER TABLE user_relations DROP FOREIGN KEY FK_148C329CA76ED395');
        $this->addSql('ALTER TABLE user_relations DROP FOREIGN KEY FK_148C329C62894749');
        $this->addSql('DROP TABLE campaign');
        $this->addSql('DROP TABLE figure');
        $this->addSql('DROP TABLE game');
        $this->addSql('DROP TABLE message');
        $this->addSql('DROP TABLE prophecy_advantage');
        $this->addSql('DROP TABLE prophecy_advantage_category');
        $this->addSql('DROP TABLE prophecy_age');
        $this->addSql('DROP TABLE prophecy_armor');
        $this->addSql('DROP TABLE prophecy_armor_category');
        $this->addSql('DROP TABLE prophecy_benefit');
        $this->addSql('DROP TABLE prophecy_caracteristic');
        $this->addSql('DROP TABLE prophecy_carrier');
        $this->addSql('DROP TABLE prophecy_caste');
        $this->addSql('DROP TABLE prophecy_currency');
        $this->addSql('DROP TABLE prophecy_disadvantage');
        $this->addSql('DROP TABLE prophecy_discipline');
        $this->addSql('DROP TABLE prophecy_favour');
        $this->addSql('DROP TABLE prophecy_figure');
        $this->addSql('DROP TABLE prophecy_figures_weapons');
        $this->addSql('DROP TABLE prophecy_figures_armors');
        $this->addSql('DROP TABLE prophecy_figures_shields');
        $this->addSql('DROP TABLE prophecy_figures_spells');
        $this->addSql('DROP TABLE prophecy_figures_advantages');
        $this->addSql('DROP TABLE prophecy_figures_disadvantages');
        $this->addSql('DROP TABLE prophecy_figures_technics');
        $this->addSql('DROP TABLE prophecy_figures_favours');
        $this->addSql('DROP TABLE prophecy_figures_benefits');
        $this->addSql('DROP TABLE prophecy_figures_prohibiteds');
        $this->addSql('DROP TABLE prophecy_figure_caracteristic');
        $this->addSql('DROP TABLE prophecy_figure_currency');
        $this->addSql('DROP TABLE prophecy_figure_discipline');
        $this->addSql('DROP TABLE prophecy_figure_major_attribute');
        $this->addSql('DROP TABLE prophecy_figure_minor_attribute');
        $this->addSql('DROP TABLE prophecy_figure_skill');
        $this->addSql('DROP TABLE prophecy_figure_spell');
        $this->addSql('DROP TABLE prophecy_figure_sphere');
        $this->addSql('DROP TABLE prophecy_figure_tendency');
        $this->addSql('DROP TABLE prophecy_figure_wound');
        $this->addSql('DROP TABLE prophecy_major_attribute');
        $this->addSql('DROP TABLE prophecy_minor_attribute');
        $this->addSql('DROP TABLE prophecy_nation');
        $this->addSql('DROP TABLE prophecy_omen');
        $this->addSql('DROP TABLE prophecy_prohibited');
        $this->addSql('DROP TABLE prophecy_shield');
        $this->addSql('DROP TABLE prophecy_skill');
        $this->addSql('DROP TABLE prophecy_skill_category');
        $this->addSql('DROP TABLE prophecy_spell');
        $this->addSql('DROP TABLE prophecy_sphere');
        $this->addSql('DROP TABLE prophecy_start_caracteristic');
        $this->addSql('DROP TABLE prophecy_start_major_attribute');
        $this->addSql('DROP TABLE prophecy_start_skill');
        $this->addSql('DROP TABLE prophecy_status');
        $this->addSql('DROP TABLE prophecy_technic');
        $this->addSql('DROP TABLE prophecy_tendency');
        $this->addSql('DROP TABLE prophecy_weapon');
        $this->addSql('DROP TABLE prophecy_weapon_category');
        $this->addSql('DROP TABLE prophecy_wound');
        $this->addSql('DROP TABLE prophecy_xpincrease');
        $this->addSql('DROP TABLE thread');
        $this->addSql('DROP TABLE user');
        $this->addSql('DROP TABLE user_relations');
    }
}
