############################################################   
#    name      : routes.yaml
#    Role      : routes list of the app.
#    author    : tristesire
#    date      : 18/03/2022
#
#     platform
#     user
#     member 
#       messages
#       figure
#       campaign
#     admin
#     game
#     prophecy
#       caste
#       characteristic
#       world
#       item
#       magic
#       start stats
#
#       
#
############################################################
        
    
############################################################
# ATTENTION IL FAUDRA PREFIXER LES ROUTES POUR LES JEUX
############################################################    
    
########## PLATFORM ##########

index:
    path: /
    controller: App\Controller\Platform\PlatformController::homepage

homepage:
    path: /homepage
    controller: App\Controller\Platform\PlatformController::homepage
    
member_homepage:
    path: /member/homepage
    controller: App\Controller\Platform\PlatformController::memberHomepage    
    
features:
    path: /features
    controller: App\Controller\Platform\PlatformController:features    
    
help:
    path: /help
    controller: App\Controller\Platform\PlatformController:help    

########## USER ##########

login:
    path: /login
    controller: App\Controller\User\SecurityController::login

registration:
    path: /registration
    controller: App\Controller\User\RegistrationController::registration

logout:
    path: /logout
    
    
profile:
    path: /member/profile/{id}
    controller: App\Controller\User\ProfileController::profile
    
relations:
    path: /member/relations
    controller: App\Controller\User\ProfileController::relations   
    
relation_add:
    path: /member/relation/add/{id}
    controller: App\Controller\User\ProfileController::relationAdd   
    
find:
    path: /member/find-profile
    controller: App\Controller\User\ProfileController::findProfile
    
#a enlever, pour tester    
my_relations:
    path: /member/relations/list
    controller: App\Controller\User\ProfileController::getRelations   
    
##########  MEMBER ##########
## MESSAGES ##
messages:
    path: /member/messages
    controller: App\Controller\Platform\Message\MessageController:messages 

new_message:
    path: /member/new-message
    controller: App\Controller\Platform\Message\MessageController:newMessage
    
delete_message:
    path: /member/delete-message{id}
    controller: App\Controller\Platform\Message\MessageController:deleteMessage   

message_response:
    path: /member/message{id}
    controller: App\Controller\Platform\Message\MessageController:messageResponse   
    
ask_campaign_invitation:
    path: /member/message/ask-invitation/campaign{id}
    controller: App\Controller\Game\CampaignController:askCampaignInvitation
    
send_campaign_invitation:   
    path: /member/message/send-invitation/campaign{id}
    controller: App\Controller\Game\CampaignController:sendCampaignInvitation
    
contact:
    path: /member/message/contact
    controller: App\Controller\Platform\Message\MessageController:contact    

## FIGURE ##
figures:
    path: /member/figures
    controller: App\Controller\Game\FigureController:figures
    

figure_find:        #redirect to the figure by owner and game
    path: /member/figure/figure-caracteristics/{id}/{game}
    controller:  App\Controller\Game\FigureController:figureFind 
    
## CAMPAIGN ##    
campaigns:
    path: /member/campaign/campaigns
    controller: App\Controller\Game\CampaignController:campaigns
    
create_campaign:
    path: /member/campaign/create
    controller: App\Controller\Game\CampaignController:newCampaign   
    
campaign:
    path: /member/campaign/campaign{id}
    controller: App\Controller\Game\CampaignController:viewCampaign
                 
find_campaigns:
    path: /member/campaign/list
    controller: App\Controller\Game\CampaignController:findCampaigns

see_other_campaign:
    path: /member/campaign/other/campaign{id}
    controller: App\Controller\Game\CampaignController:seeOtherCampaign 
    
campaign_add_component:
    path: member/campaign/{id}/find/add-component
    controller: App\Controller\Game\CampaignController:findAddComponent 
    
campaign_figures:
    path: member/campaign/{id}/figures
    controller: App\Controller\Game\CampaignController:findFigures
       
########## ADMIN ##########
new_game:
    path: /admin/new-game
    controller: App\Controller\Game\GameController::new 

admin:
    path: /admin/homepage
    controller: App\Controller\Platform\PlatformController::adminHomepage
 
setup:
    path: /admin/setup/{id}
    controller: App\Controller\Game\GameController::setup  
    
########## SADMIN ##########    
admin_users:
    path: /sadmin/users
    controller: App\Controller\User\SecurityController::adminUser
    
########## GAME ##########
available_games:
    path: /games
    controller: App\Controller\Game\GameController:games

####### PROPHECY #######  

## START STATS ##

setup_prophecy:     
    path: /admin/setup-prophecy
    controller: App\Controller\Game\Prophecy\Game\StatsInitController::setupProphecy

prophecy_create_xp_increase:
    path: /{role}/campaign/{id}/prophecy/new-xp-increase
    controller: App\Controller\Game\Prophecy\Game\StatsInitController::newXPIncrease

prophecy_create_start_caracteristics:
    path: /{role}/campaign/{id}/prophecy/new-start-caracteristics
    controller: App\Controller\Game\Prophecy\Game\StatsInitController::newStartCaracteristics
        
    
## CASTE ##
prophecy_create_caste:
    path: /{role}/campaign/{id}/prophecy/new-caste          
    controller: App\Controller\Game\Prophecy\Game\Caste\CasteController::newCaste

prophecy_create_benefit:
    path: /{role}/campaign/{id}/prophecy/new-benefit
    controller: App\Controller\Game\Prophecy\Game\Caste\CasteController::newBenefit

prophecy_create_status:
    path: /{role}/campaign/{id}/prophecy/new-status
    controller: App\Controller\Game\Prophecy\Game\Caste\CasteController::newStatus

prophecy_create_prohibited:
    path: /{role}/campaign/{id}/prophecy/new-prohibited
    controller: App\Controller\Game\Prophecy\Game\Caste\CasteController::newProhibited

prophecy_create_favour:
    path: /{role}/campaign/{id}/prophecy/new-favour
    controller: App\Controller\Game\Prophecy\Game\Caste\CasteController::newFavour

prophecy_create_technic:
    path: /{role}/campaign/{id}/prophecy/new-technic
    controller: App\Controller\Game\Prophecy\Game\Caste\CasteController::newTechnic

## CHARACTERISTIC ##
prophecy_create_advantage_category:
    path: /{role}/campaign/{id}/prophecy/new-advantage-category
    controller: App\Controller\Game\Prophecy\Game\Characteristic\CharacteristicController::newAdvantageCategory

prophecy_create_advantage:
    path: /{role}/campaign/{id}/prophecy/new-advantage
    controller: App\Controller\Game\Prophecy\Game\Characteristic\CharacteristicController::newAdvantage

prophecy_create_caracteristic:
    path: /{role}/campaign/{id}/prophecy/new-caracteristic
    controller: App\Controller\Game\Prophecy\Game\Characteristic\CharacteristicController::newCaracteristic

prophecy_create_age:
    path: /{role}/campaign/{id}/prophecy/new-age
    controller: App\Controller\Game\Prophecy\Game\Characteristic\CharacteristicController::newAge

prophecy_create_disadvantage:
    path: /{role}/campaign/{id}/prophecy/new-disadvantage
    controller: App\Controller\Game\Prophecy\Game\Characteristic\CharacteristicController::newDisadvantage

prophecy_create_omen:
    path: /{role}/campaign/{id}/prophecy/new-omen
    controller: App\Controller\Game\Prophecy\Game\Characteristic\CharacteristicController::newOmen
    
prophecy_create_major_attribute:
    path: /{role}/campaign/{id}/prophecy/new-major-attribute
    controller: App\Controller\Game\Prophecy\Game\Characteristic\CharacteristicController::newMajorAttribute
    
prophecy_create_minor_attribute:
    path: /{role}/campaign/{id}/prophecy/new-minor-attribute
    controller: App\Controller\Game\Prophecy\Game\Characteristic\CharacteristicController::newMinorAttribute        
    
prophecy_create_skill_category:
    path: /{role}/campaign/{id}/prophecy/new-skill-category
    controller: App\Controller\Game\Prophecy\Game\Characteristic\CharacteristicController::newSkillCategory    
    
prophecy_create_tendency:
    path: /{role}/campaign/{id}/prophecy/new-tendency
    controller: App\Controller\Game\Prophecy\Game\Characteristic\CharacteristicController::newTendency    
        
prophecy_create_skill:
    path: /{role}/campaign/{id}/prophecy/new-skill
    controller: App\Controller\Game\Prophecy\Game\Characteristic\CharacteristicController::newSkill   
    
prophecy_create_wound:
    path: /{role}/campaign/{id}/prophecy/new-wound
    controller: App\Controller\Game\Prophecy\Game\Characteristic\CharacteristicController::newWound      
    
## WORLD ##    
prophecy_create_currency:
    path: /{role}/campaign/{id}/prophecy/new-currency
    controller: App\Controller\Game\Prophecy\Game\World\WorldController::newCurrency       
    
prophecy_create_nation:
    path: /{role}/campaign/{id}/prophecy/new-nation
    controller: App\Controller\Game\Prophecy\Game\World\WorldController::newNation 
    
## ITEM ##
prophecy_create_weapon_category:
    path: /{role}/campaign/{id}/prophecy/new-weapon-category
    controller: App\Controller\Game\Prophecy\Game\Item\ItemController::newWeaponCategory
    
prophecy_create_armor_category:
    path: /{role}/campaign/{id}/prophecy/new-armor-category
    controller: App\Controller\Game\Prophecy\Game\Item\ItemController::newArmorCategory
    
prophecy_create_shield:
    path: /{role}/campaign/{id}/prophecy/new-shield
    controller: App\Controller\Game\Prophecy\Game\Item\ItemController::newShield
    
prophecy_create_armor:
    path: /{role}/campaign/{id}/prophecy/new-armor
    controller: App\Controller\Game\Prophecy\Game\Item\ItemController::newArmor    
    
prophecy_create_weapon:
    path: /{role}/campaign/{id}/prophecy/new-weapon
    controller: App\Controller\Game\Prophecy\Game\Item\ItemController::newWeapon

## MAGIC ##
prophecy_create_discipline:
    path: /{role}/campaign/{id}/prophecy/new-discipline
    controller: App\Controller\Game\Prophecy\Game\Magic\MagicController::newDiscipline

prophecy_create_sphere:
    path: /{role}/campaign/{id}/prophecy/new-sphere
    controller: App\Controller\Game\Prophecy\Game\Magic\MagicController::newSphere

prophecy_create_spell:
    path: /{role}/campaign/{id}/prophecy/new-spell
    controller: App\Controller\Game\Prophecy\Game\Magic\MagicController::newSpell

  
## FIGURE ##

prophecy_new_figure:
    path: /member/figure/new-figure{id}
    controller:  App\Controller\Game\Prophecy\Figure\FigureController:newFigure
    
prophecy_figure_caracteristics:
    path: /member/figure/prophecy/figure-caracteristics/{id}
    controller: App\Controller\Game\Prophecy\Figure\FigureController:figureCaracteristics   

#A ANNULER DES QUE POSSIBLE    
#figure_caracteristics:
#    path: /member/figure/figure-caracteristics/{id}
#    controller:  App\Controller\Game\Prophecy\Figure\FigureController:figureCaracteristics  
    
#route a definir avec clement qui doit etre commune, accès au  premier onglet du personnage    
    

prophecy_figure_view:
    path: /member/figure/{id}/view
    controller: App\Controller\Game\Prophecy\Figure\FigureController:figureView
    
prophecy_figure_magic:
    path: /member/figure/{id}/figure-magic
    controller:  App\Controller\Game\Prophecy\Figure\FigureController:figureMagic 

prophecy_figure_caste:
    path: /member/figure/{id}/figure-caste
    controller:  App\Controller\Game\Prophecy\Figure\FigureController:figureCaste      
    
prophecy_figure_equipment:
    path: /member/figure/{id}/figure-equipment
    controller: App\Controller\Game\Prophecy\Figure\FigureController:figureEquipment 
    
prophecy_figure_background:
    path: /member/figure/{id}/figure-background
    controller: App\Controller\Game\Prophecy\Figure\FigureController:figureBackground 
    
prophecy_edit_initial_omen:
    path: /member/figure/{id}/figure-edit-initial-omen
    controller: App\Controller\Game\Prophecy\Figure\FigureController:figureEditInitialOmen   

figure_edit_initial_caracteristic:  
    path: /member/figure/{id}/figure-edit-initial-caracteristic
    controller: App\Controller\Game\Prophecy\Figure\FigureController:figureEditInitialCaracteristic

figure_edit_initial_major_attribute:
    path: /member/figure/{id}/figure-edit-initial-major-attribute
    controller: App\Controller\Game\Prophecy\Figure\FigureController:figureEditInitialMajorAttribute
    
figure_edit_initial_minor_attribute:
    path: /member/figure/{id}/figure-edit-initial-minor-attribute
    controller: App\Controller\Game\Prophecy\Figure\FigureController:figureEditInitialMinorAttribute
    
prophecy_figure_edit_initial_caste:
    path: /member/figure/{id}/prophecy-figure-edit-initial-caste
    controller: App\Controller\Game\Prophecy\Figure\FigureController:figureEditInitialCaste
    
prophecy_figure_edit_initial_age:
    path: /member/figure/{id}/prophecy-figure-edit-initial-age
    controller: App\Controller\Game\Prophecy\Figure\FigureController:figureEditInitialAge
    
prophecy_figure_edit_initial_prohibited:
    path: /member/figure/{id}/prophecy-figure-edit-initial-prohibited
    controller: App\Controller\Game\Prophecy\Figure\FigureController:figureEditInitialProhibited
    
prophecy_edit_initial_tendency:
    path: /member/figure/{id}/prophecy-figure-edit-initial-tendency
    controller: App\Controller\Game\Prophecy\Figure\FigureController:figureEditInitialTendency
    
prophecy_figure_edit_initial_background:
    path: /member/figure/{id}/prophecy-figure-edit-initial-background
    controller: App\Controller\Game\Prophecy\Figure\FigureController:figureEditInitialBackground
    
prophecy_edit_initial_nation:
    path: /member/figure/{id}/figure-edit-initial-nation
    controller: App\Controller\Game\Prophecy\Figure\FigureController:figureEditInitialNation 
    
formulaire:
    path: /form/{id}
    controller: App\Controller\Game\Prophecy\Figure\FigureController:figureEditInitialCaracteristicTest
    
    
#delete_figure:        
    