############################################################   
#    name      : routes.yaml
#    Role      : routes list of the app.
#    author    : tristesire
#    date      : 18/03/2022
#
#     platform
#     user
#     member 
#       messages
#       figure
#       campaign
#     admin
#     game
#     prophecy
#       caste
#       characteristic
#       world
#       item
#       magic
#       start stats
#
############################################################
        
    
########## PLATFORM ##########

index:
    path: /
    controller: App\Controller\Platform\PlatformController::homepage

homepage:
    path: /homepage
    controller: App\Controller\Platform\PlatformController::homepage
    
member_homepage:
    path: /member/homepage
    controller: App\Controller\Platform\PlatformController::memberHomepage    
    
features:
    path: /features
    controller: App\Controller\Platform\PlatformController:features    
    
help:
    path: /help
    controller: App\Controller\Platform\PlatformController:help    

########## USER ##########

login:
    path: /login
    controller: App\Controller\User\SecurityController::login

registration:
    path: /registration
    controller: App\Controller\User\RegistrationController::registration

logout:
    path: /logout
    
    
profile:
    path: /member/profile
    controller: App\Controller\User\ProfileController::profile
    
##########  MEMBER ##########
## MESSAGES ##
messages:
    path: /member/messages
    controller: App\Controller\Platform\Message\MessageController:messages 

new_message:
    path: /member/new-message
    controller: App\Controller\Platform\Message\MessageController:newMessage
    
delete_message:
    path: /member/delete-message{id}
    controller: App\Controller\Platform\Message\MessageController:deleteMessage   

message_response:
    path: /member/message{id}
    controller: App\Controller\Platform\Message\MessageController:messageResponse   
    
ask_campaign_invitation:
    path: /member/message/ask-invitation/campaign{id}
    controller: App\Controller\Platform\Message\MessageController:askCampaignInvitation
    
send_campaign_invitation:   
    path: /member/message/send-invitation/campaign{id}
    controller: App\Controller\Platform\Message\MessageController:sendCampaignInvitation
    
contact:
    path: /member/message/contact
    controller: App\Controller\Platform\Message\MessageController:contact

## FIGURE ##
figures:
    path: /member/figures
    controller: App\Controller\Game\Prophecy\Figure\FigureController:figures

new_figure:
    path: /member/figure/new-figure{id}
    controller:  App\Controller\Game\Prophecy\Figure\FigureController:newFigure
    
figure_caracteristics:
    path: /member/figure/figure-caracteristics/{id}
    controller:  App\Controller\Game\Prophecy\Figure\FigureController:figureCaracteristics   
    
figure_magic:
    path: /member/figure/figure-magic/{id}
    controller:  App\Controller\Game\Prophecy\Figure\FigureController:figureMagic 

figure_caste:
    path: /member/figure/figure-caste/{id}
    controller:  App\Controller\Game\Prophecy\Figure\FigureController:figureCaste      
    
figure_equipment:
    path: /member/figure/figure-equipment/{id}
    controller: App\Controller\Game\Prophecy\Figure\FigureController:figureEquipment 
    
figure_background:
    path: /member/figure/figure-background/{id}
    controller: App\Controller\Game\Prophecy\Figure\FigureController:figureBackground 

figure_edit_initial_caracteristic:  
    path: /member/figure/figure-edit-initial-caracteristic/{id}
    controller: App\Controller\Game\Prophecy\Figure\FigureController:figureEditInitialCaracteristic
    
formulaire:
    path: /form/{id}
    controller: App\Controller\Game\Prophecy\Figure\FigureController:figureEditInitialCaracteristicTest
    
figure_edit_initial_major_attribute:
    path: /member/figure/figure-edit-initial-major-attribute/{id}
    controller: App\Controller\Game\Prophecy\Figure\FigureController:figureEditInitialMajorAttribute
    
#delete_figure:    
    
## CAMPAIGN ##    
campaigns:
    path: /member/campaign/campaigns
    controller: App\Controller\Campaign\CampaignController:campaigns
    
create_campaign:
    path: /member/campaign/create
    controller: App\Controller\Campaign\CampaignController:newCampaign   
    
campaign:
    path: /member/campaign/campaign{id}
    controller: App\Controller\Campaign\CampaignController:viewCampaign
                 
find_campaigns:
    path: /member/campaign/list
    controller: App\Controller\Campaign\CampaignController:findCampaigns

see_other_campaign:
    path: /member/campaign/other/campaign{id}
    controller: App\Controller\Campaign\CampaignController:seeOtherCampaign    
       
########## ADMIN ##########
new_game:
    path: /admin/new-game
    controller: App\Controller\Game\GameController::new 

admin:
    path: /admin/homepage
    controller: App\Controller\Platform\PlatformController::adminHomepage

setup_prophecy:
    path: /admin/setup-prophecy
    controller: App\Controller\Platform\PlatformController::setupProphecy
    
setup:
    path: /admin/setup/{id}
    controller: App\Controller\Platform\PlatformController::setup   
    
setup_PROPHECY:     
    path: /admin/setup-prophecy
    controller: App\Controller\Platform\PlatformController::setupProphecy 
    
########## GAME ##########
available_games:
    path: /games
    controller: App\Controller\Game\GameController:games

####### PROPHECY #######      
## CASTE ##
create_caste:
    path: /admin/new-caste
    controller: App\Controller\Game\Prophecy\Game\Caste\CasteController::newCaste

create_benefit:
    path: /admin/new-benefit
    controller: App\Controller\Game\Prophecy\Game\Caste\CasteController::newBenefit

create_status:
    path: /admin/new-status
    controller: App\Controller\Game\Prophecy\Game\Caste\CasteController::newStatus

create_prohibited:
    path: /admin/new-prohibited
    controller: App\Controller\Game\Prophecy\Game\Caste\CasteController::newProhibited

create_favour:
    path: /admin/new-favour
    controller: App\Controller\Game\Prophecy\Game\Caste\CasteController::newFavour

create_technic:
    path: /admin/new-technic
    controller: App\Controller\Game\Prophecy\Game\Caste\CasteController::newTechnic

## CHARACTERISTIC ##
create_advantage_category:
    path: /admin/new-advantage-category
    controller: App\Controller\Game\Prophecy\Game\Characteristic\CharacteristicController::newAdvantageCategory

create_advantage:
    path: /admin/new-advantage
    controller: App\Controller\Game\Prophecy\Game\Characteristic\CharacteristicController::newAdvantage

create_caracteristic:
    path: /admin/new-caracteristic
    controller: App\Controller\Game\Prophecy\Game\Characteristic\CharacteristicController::newCaracteristic

create_age:
    path: /admin/new-age
    controller: App\Controller\Game\Prophecy\Game\Characteristic\CharacteristicController::newAge

create_disadvantage:
    path: /admin/new-disadvantage
    controller: App\Controller\Game\Prophecy\Game\Characteristic\CharacteristicController::newDisadvantage

create_omen:
    path: /admin/new-omen
    controller: App\Controller\Game\Prophecy\Game\Characteristic\CharacteristicController::newOmen
    
create_major_attribute:
    path: /admin/new-major-attribute
    controller: App\Controller\Game\Prophecy\Game\Characteristic\CharacteristicController::newMajorAttribute
    
create_minor_attribute:
    path: /admin/new-minor-attribute
    controller: App\Controller\Game\Prophecy\Game\Characteristic\CharacteristicController::newMinorAttribute        
    
create_skill_category:
    path: /admin/new-skill-category
    controller: App\Controller\Game\Prophecy\Game\Characteristic\CharacteristicController::newSkillCategory    
    
create_tendency:
    path: /admin/new-tendency
    controller: App\Controller\Game\Prophecy\Game\Characteristic\CharacteristicController::newTendency    
        
create_skill:
    path: /admin/new-skill
    controller: App\Controller\Game\Prophecy\Game\Characteristic\CharacteristicController::newSkill   
    
create_wound:
    path: /admin/new-wound
    controller: App\Controller\Game\Prophecy\Game\Characteristic\CharacteristicController::newWound      
    
## WORLD ##    
create_currency:
    path: /admin/new-currency
    controller: App\Controller\Game\Prophecy\Game\World\WorldController::newCurrency       
    
create_nation:
    path: /admin/new-nation
    controller: App\Controller\Game\Prophecy\Game\World\WorldController::newNation 
    
## ITEM ##
create_weapon_category:
    path: /admin/new-weapon-category
    controller: App\Controller\Game\Prophecy\Game\Item\ItemController::newWeaponCategory
    
create_armor_category:
    path: /admin/new-armor-category
    controller: App\Controller\Game\Prophecy\Game\Item\ItemController::newArmorCategory
    
create_shield:
    path: /admin/new-shield
    controller: App\Controller\Game\Prophecy\Game\Item\ItemController::newShield
    
create_armor:
    path: /admin/new-armor
    controller: App\Controller\Game\Prophecy\Game\Item\ItemController::newArmor    
    
create_weapon:
    path: /admin/new-weapon
    controller: App\Controller\Game\Prophecy\Game\Item\ItemController::newWeapon

## MAGIC ##
create_discipline:
    path: /admin/new-discipline
    controller: App\Controller\Game\Prophecy\Game\Magic\MagicController::newDiscipline

create_sphere:
    path: /admin/new-sphere
    controller: App\Controller\Game\Prophecy\Game\Magic\MagicController::newSphere

create_spell:
    path: /admin/new-spell
    controller: App\Controller\Game\Prophecy\Game\Magic\MagicController::newSpell

## START STATS ##
create_xp_increase:
    path: /admin/new-xp-increase
    controller: App\Controller\Game\Prophecy\Game\StatsInitController::newXPIncrease

create_start_caracteristics:
    path: /admin/new-start-caracteristics
    controller: App\Controller\Game\Prophecy\Game\StatsInitController::newStartCaracteristics
          
    
    